# Generated by Django 3.2.16 on 2023-06-25 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания (автоматическое)')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('description', models.CharField(max_length=1000, verbose_name='описание')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания (автоматическое)')),
                ('name', models.CharField(max_length=256, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'географическая метка',
                'verbose_name_plural': 'географические метки',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания (автоматическое)')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('text', models.CharField(max_length=1000, verbose_name='текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата, время')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='автор', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='категория', to='blog.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='географическая_метка', to='blog.location')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
